name: "aarch64 macOS/darwin"
on:
  pull_request:
  push:
jobs:
  build-configuration:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v12
    - name: Install Cachix
      uses: cachix/cachix-action@v15
      with:
        name: thomaschrstnsn
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Darwin configuration
      run: ./build.sh darwin aeris
