name: "x64 Linux"
on:
  pull_request:
  push:
jobs:
  build-configuration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Atlas, enix] # disabled: aero-nix
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v12
    - name: Install Cachix
      uses: cachix/cachix-action@v15
      with:
        name: thomaschrstnsn
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build NixOS configuration
      run: ./build.sh nixos '${{ matrix.configuration }}'
