name: "x64 Linux"
on:
  pull_request:
  push:
jobs:
  build-configuration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [PC04236, Atlas, aero-nix]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: mycache
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./build.sh nixos '${{ matrix.configuration }}'
