name: "x64 macOS"
on:
  pull_request:
  push:
jobs:
  build-configuration:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v24
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: thomaschrstnsn
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./build.sh darwin A125228-DK
