name: "x64 macOS"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v24
    - uses: cachix/cachix-action@v12
      with:
        name: mycache
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./build.sh darwin A125228-DK
