name: "x64 macOS/darwin"
on:
  pull_request:
  push:
jobs:
  build-configuration:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Install Cachix
      uses: cachix/cachix-action@v12
      with:
        name: thomaschrstnsn
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Darwin configuration
      run: ./build.sh darwin ci-x64-darwin
